name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install npcap sdk
      shell: bash
      run: |
        mkdir $TEMP/npcap-sdk
        pushd $TEMP/npcap-sdk
        curl -O https://nmap.org/npcap/dist/npcap-sdk-1.05.zip
        7z x npcap-sdk-1.05.zip -o.
        ls -l $TEMP/npcap-sdk/Lib/x64
        # echo "::set-env LIB=$LIB:$TEMP/npcap-sdk/Lib/x64"
        popd
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      shell: bash
      run: env LIB=$TEMP/npcap-sdk/Lib/x64/ cargo test --verbose
    - name: Clean up
      shell: bash
      run: rm -r $TEMP/npcap-sdk